# Copyright 2019-2020 Emir Turkes, Columbia University Medical Center
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"

services:
  all:
    image: eturkes/bag3-co-ip:R3.6.0v5
    volumes:
      - ".:/bag3-co-ip:rw"
    command: Rscript -e "setwd('/bag3-co-ip/R/')" -e "rmarkdown::render('bag3_co_ip_report.Rmd', output_file = '../results/bag3-co-ip-report.html')"

  rstudio:
    image: eturkes/bag3-co-ip:R3.6.0v5
    volumes:
      - ".:/home/rstudio/bag3-co-ip:rw"
    ports:
      - "127.0.0.1:8789:8787"
    environment:
      -  DISABLE_AUTH=true
