---
title: "BAG3 Co-IP MS Analysis"
author: "Emir Turkes"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output:
    html_document:
        number_sections: yes
        theme: united
        toc: yes
        toc_float:
            collapsed: no
            smooth_scroll: no
knit: (
    function(inputFile, encoding) {
        rmarkdown::render(
            inputFile,
            encoding = encoding,
            output_file = "../gdrive/results/bag3-co-ip-analysis.html"
            )
        }
    )
---

```{r license, include=FALSE}
#    This file is part of bag3-co-ip.
#    Copyright (C) 2019  Emir Turkes
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Emir Turkes can be contacted at eturkes@bu.edu
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
